c_compiler: vs2015
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: vs2015
extend_keys:
- ignore_build_only_deps
- extend_keys
- pin_run_as_build
- ignore_version
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
lua: '5'
numpy: '1.11'
perl: 5.26.0
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x.x
    max_pin: x.x.x
python: '3.7'
r_base: '3.4'
target_platform: win-64
vc: '14'
