numpy:
- '1.11'
perl:
- '5.26'
lua:
- '5'
r_base:
- '3.5'
cpu_optimization_target:
- nocona
cran_mirror:
- https://mran.microsoft.com/snapshot/2018-01-01
target_platform:
- win-64
fortran_compiler:
- intel-fortran
noarch_python:
- 'False'
apr:
- 1.6.3
blas_impl:
- openblas
- mkl
boost:
- '1.67'
bzip2:
- '1.0'
cairo:
- '1.14'
VERBOSE_AT:
- V=1
VERBOSE_CM:
- VERBOSE=1
ctng_binutils:
- 2.31.1
ctng_duma:
- 2.5.15
ctng_gmp:
- 6.1.2
ctng_isl:
- '0.19'
ctng_libc:
- gnu
ctng_kernel:
- 2.6.32
ctng_libiconv:
- '1.15'
ctng_mpc:
- '1'
ctng_nature:
- shared
ctng_ncurses:
- 7.3.0
- '6.1'
dbus:
- '1'
expat:
- '2.2'
fontconfig:
- '2.13'
freetype:
- '2.9'
g2clib:
- '1.6'
gstreamer:
- '1.14'
gst_plugins_base:
- '1.14'
geos:
- 3.6.2
giflib:
- '5.1'
glib:
- '2.56'
gmp:
- '6.1'
gnu:
- 2.12.2
harfbuzz:
- '1.7'
hdf4:
- '4.2'
hdf5:
- '1.10'
- '1.8'
hdfeos2:
- '2.20'
hdfeos5:
- '5.1'
icu:
- '58'
jpeg:
- '9'
libdap4:
- '3.19'
libffi:
- '3.2'
libgd:
- 2.2.5
libgdal:
- '2.2'
libgsasl:
- '1.8'
libkml:
- '1.3'
libnetcdf:
- '4.6'
libpng:
- '1.6'
libtiff:
- '4.0'
libwebp:
- 1.0.0
libxml2:
- '2.9'
libxslt:
- '1.1'
lzo:
- '2'
macos_min_version:
- '10.9'
macos_machine:
- x86_64-apple-darwin13.4.0
MACOSX_DEPLOYMENT_TARGET:
- '10.9'
mkl:
- '2018'
mpfr:
- '4'
openblas:
- 0.3.3
openjpeg:
- '2.3'
openssl:
- 1.0.2
pixman:
- '0.34'
proj4:
- '5'
libprotobuf:
- 3.6.0
r_version:
- 3.5.0
r_implementation:
- mro-base
- r-base
serf:
- 1.3.9
sqlite:
- '3'
cross_compiler_target_platform:
- win-64
- win-32
tk:
- '8.6'
zlib:
- '1.2'
xz:
- '5'
qtwebkit:
- 'true'
update_version:
- '8'
cl_version:
- 19.15.26726
runtime_version:
- 14.15.26706
ctng_gcc_activation_build_number:
- '1'
- '3'
fortran_compiler_version:
- 16.0.4
- 13.1.6
- 16.0.4
- 16.0.4
python:
- '3.5'
- '2.7'
- '3.7'
- '3.6'
vc:
- '14'
- '9'
- '14'
- '14'
ctng_gcc:
- 8.2.0
- 7.3.0
ignore_build_only_deps:
- numpy
- python
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x.x
    max_pin: x.x.x
  libboost:
    max_pin: x.x.x
cxx_compiler:
- vs2015
- vs2008
- vs2015
- vs2015
c_compiler:
- vs2015
- vs2008
- vs2015
- vs2015
ctng_gcc_build_number:
- '2'
- '1'
zip_keys:
- - vc
  - c_compiler
  - cxx_compiler
  - fortran_compiler_version
  - python
- - ctng_gcc
  - ctng_gcc_build_number
  - ctng_gcc_activation_build_number
